"""Scoped stdio MCP files for native applications. Provider OAuth secrets are never read."""
from pathlib import Path
import json, os, shlex, shutil, subprocess, sys
from .common import BridgeError, atomic_json, private
from .providers import native_login_command

def prepare_mcp(root,entity,turn,base,token):
    credentials=Path(root)/'native-pairings'/(turn+'.json')
    atomic_json(credentials,{'base':base,'token':token,'actor':entity})
    return {'command':sys.executable,'args':['-m','lelock_tavern.mcp_stdio','--pairing',str(credentials)],
            'env':{'PYTHONPATH':str(Path(__file__).resolve().parents[1])}}

def launch_native_login(root,provider):
    try:argv=native_login_command(provider)
    except KeyError:raise BridgeError('Choose a supported native login')
    binary=shutil.which(argv[0])
    if not binary:raise BridgeError('Install the official '+argv[0]+' application first; no download was run')
    argv[0]=binary
    if sys.platform!='darwin':
        return {'native_login_required':True,'command':shlex.join(argv),'launched':False}
    folder=private(Path(root)/'login-launchers');script=folder/(provider+'.command')
    if script.exists() or script.is_symlink():
        # Only replace an exact file previously generated by this module, never an arbitrary script.
        if script.is_symlink() or not script.read_text().startswith('#!/bin/sh\n# Lelock native login\n'):
            raise BridgeError('Existing launcher is not owned by Lelock')
    script.write_text('#!/bin/sh\n# Lelock native login\nexec '+shlex.join(argv)+'\n');script.chmod(0o700)
    subprocess.run(['/usr/bin/open','-a','Terminal',str(script)],check=True,timeout=10)
    return {'native_login_required':True,'launched':True,'provider':provider,
            'note':'Authenticate in the unmodified native application. This gateway does not collect credentials.'}
